[package]
name = "supertroupers"
version = "0.1.0"
authors = ["minauteur <Thompennington@gmail.com>"]

[dependencies]
rand = "0.3"
# slog = "*"
hyphenation = "0.6"
text_io = "*"
markov = "*"
# serde = "*"